import { useMemo, useState } from "react";
import ProductCard from "./components/ProductCard.jsx";
export default function ProductCatalog({ products, onAdd, onDetail, offersOnly = false }) {
 const [category,setCategory]=useState("Todos");const [query,setQuery]=useState("");
 const source=offersOnly?products.filter(p=>p.featured||p.category==="Ofertas"):products;
 const categories=["Todos",...new Set(source.map(p=>p.category))];
 const filtered=useMemo(()=>source.filter(p=>(category==="Todos"||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase())),[source,category,query]);
 return <section id={offersOnly?"ofertas":"productos"} className={`py-5 ${offersOnly?"":"bg-light"}`}><div className="container"><div className="row align-items-end mb-4"><div className="col-lg-7"><span className="text-primary fw-semibold">{offersOnly?"DESTACADOS Y OFERTAS":"CATÁLOGO"}</span><h2 className="display-6 fw-bold">{offersOnly?"Productos destacados":"Productos para tu hogar y negocio"}</h2></div><div className="col-lg-5 mt-3"><label htmlFor={offersOnly?"offer-search":"product-search"} className="form-label">Buscar producto</label><input id={offersOnly?"offer-search":"product-search"} className="form-control" placeholder="Buscar producto..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="d-flex flex-wrap gap-2 mb-4">{categories.map(c=><button key={c} className={`btn ${category===c?"btn-primary":"btn-outline-primary"}`} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="row g-4">{filtered.map(p=><div className="col-12 col-sm-6 col-lg-4 col-xl-3" key={p.id}><ProductCard product={p} onAdd={onAdd} onDetail={onDetail}/></div>)}</div>{filtered.length===0&&<div className="alert alert-warning mt-4">No encontramos productos para tu búsqueda.</div>}</div></section>;
}
